export type LetterTier = "S" | "A" | "B" | "C" | "D" | "E" | "F" | "I";

/** Mirrors `FinanceSystem.normalize_finances` / save `finances` block. */
export interface Finances {
  status: string;
  currency: string;
  cash_yen: number;
  opening_cash_yen: number;
  last_processed_date: string | null;
  ledger: DailyBreakdown[];
  notes: string;
}

/** One row from `FinanceSystem.build_daily_breakdown`. */
export interface DailyBreakdown {
  date: string;
  tier: string;
  income_total: number;
  expense_total: number;
  net_total: number;
  digital_sales: number;
  fan_meetings: number;
  goods: number;
  media: number;
  live_tickets: number;
  live_goods: number;
  tokutenkai_revenue: number;
  staff: number;
  office: number;
  promotion: number;
  live_cost: number;
  live_ops_cost: number;
  live_venue_fee: number;
  tokutenkai_cost: number;
  tokutenkai_idol_share: number;
  salaries: number;
  scout_retainers: number;
  media_passive_removed?: number;
  media_event_revenue?: number;
  media_operating_cost?: number;
  media_event_travel?: number;
  media_event_making?: number;
  media_event_advertising?: number;
  media_event_staffing?: number;
  media_fixed_admin?: number;
  media_fixed_advertising?: number;
  media_event_count?: number;
  media_event_popularity_gain?: number;
  media_event_fan_gain?: number;
  cd_release_count?: number;
  cd_release_units?: number;
  cd_release_revenue?: number;
  cd_release_mv_cost?: number;
  live_ticket_revenue?: number;
  live_goods_revenue?: number;
  post_live_tokutenkai_revenue?: number;
  online_benefit_revenue?: number;
  shooting_handshake_revenue?: number;
  release_sales_revenue?: number;
  digital_streaming_revenue?: number;
  media_appearance_revenue?: number;
  commercial_ip_revenue?: number;
  fanclub_revenue?: number;
  birthday_special_revenue?: number;
  cheki_gross_revenue?: number;
  cheki_ops_cost?: number;
  cheki_member_share?: number;
  cheki_net_profit?: number;
  cd_net_profit?: number;
  member_base_compensation?: number;
  member_sales_share?: number;
  member_monthly_income_total?: number;
  staff_payroll?: number;
  office_admin_cost?: number;
  promotion_cost?: number;
  benefit_ops_cost?: number;
  production_cost?: number;
  goods_cost?: number;
  live_ticket_count_estimate?: number;
  fanclub_members_estimate?: number;
  cd_units_sold?: number;
  online_signing_member_seconds?: number;
  public_fans_estimate?: number;
  otaku_fans_estimate?: number;
  core_fans_estimate?: number;
  female_fan_share_estimate?: number;
  youth_fan_share_estimate?: number;
  middle_plus_fan_share_estimate?: number;
  fanclub_demand_multiplier?: number;
  cheki_demand_multiplier?: number;
  goods_demand_multiplier?: number;
  digital_demand_multiplier?: number;
  release_demand_multiplier?: number;
  member_hours_live?: number;
  member_hours_benefit?: number;
  member_hours_media?: number;
  member_hours_training?: number;
  revenue_per_member_hour?: number;
}
